### ISSUE TITLE
Previously loaded pages stacking at the bottom

### ISSUE THREAD

**Issue by scott-dowell** [GaryGadget9/WiseTree-frontend#2]
When you navigate between screens the previous screen appears below.
![image](https://user-images.githubusercontent.com/85996333/170231682-8d81bcac-5633-4685-8784-4408e351e52a.png)

**Comment by GaryGadget9** [comment]
Fixed with https://github.com/GaryGadget9/WiseTree-frontend/commit/4418f5a95faa9eb0db69fcb870bfe03d6619dda7
